_wandb:
    value:
        cli_version: 0.22.3
        e:
            z8ctgv9oflinimx3iy5b6rezdj8bjocu:
                codePath: c:\Users\nikol\OneDrive\Tugas Akhir\code\merge.ipynb
                codePathLocal: merge.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "510263627776"
                        used: "479247601664"
                email: nikolaarinanda01@gmail.com
                executable: c:\Users\nikol\miniconda3\envs\ta\python.exe
                git:
                    commit: 3ace9b4ee4f034258b8903472667a69ccc049d7d
                    remote: https://github.com/nikolaarinanda/tugas-akhir.git
                host: Nikola
                memory:
                    total: "25131765760"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\nikol\OneDrive\Tugas Akhir\code\merge.ipynb
                python: CPython 3.13.7
                root: c:\Users\nikol\OneDrive\Tugas Akhir\code
                startedAt: "2026-01-16T10:46:18.056619Z"
                writerId: z8ctgv9oflinimx3iy5b6rezdj8bjocu
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "6": 4.56.2
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
        visualize:
            val_confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: val_confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 100
conv_filters:
    value: 50
dataset_path:
    value: ../dataset/cyberbullying.csv
dropout:
    value: 0.5
embed_dim:
    value: 100
epochs:
    value: 100
kernel_size:
    value:
        - 3
        - 4
lr:
    value: 0.005
max_length:
    value: 128
n_folds:
    value: 5
num_classes:
    value: 2
output_dir:
    value: model_outputs
output_model:
    value: true
patience:
    value: 5
seed:
    value: 29082002
tokenizer:
    value: indobenchmark/indobert-base-p1
use_wandb:
    value: false
wandb_group:
    value: Light TextCNN batch size ablation
wandb_note:
    value: Light TextCNN batch size ablation
