_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.11
            "6": 4.51.2
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 16
dropout:
    value: 0.1
embed_dim:
    value: 128
epochs:
    value: 50
file_path:
    value: ../dataset/cyberbullying.csv
kernel_size:
    value:
        - 2
        - 4
lr:
    value: 0.005
max_length:
    value: 128
min_delta:
    value: 0.001
n_folds:
    value: 5
num_classes:
    value: 2
num_filters:
    value: 100
out_channels:
    value: 50
output_dir:
    value: model_outputs
output_model:
    value: false
patience:
    value: 5
seed:
    value: 29082002
tokenizer:
    value: indobenchmark/indobert-base-p1
use_wandb:
    value: true
